### ISSUE TITLE
RuntimeError('MD5 checksum failed.')

### ISSUE THREAD

**Issue by sephiartlist** [jina-ai/example-video-search#6]
Hi,
l'm starting to get `MD5 checksum failed` errors on various files.
I've run a clean installation of the example and I'm getting the following error
```sh
frame_extractor@63989[E]:Error while pulling jinahub://VideoLoader/v0.3: 
RuntimeError('MD5 checksum failed.')
```
Updated to `jinahub://VideoLoader/v0.4`

But then I got an error for  SimpleIndexer
```sh
image_indexer@75458[E]:Error while pulling jinahub://SimpleIndexer/v0.4: 
RuntimeError('MD5 checksum failed.')
```
I then updated to jinahub://SimpleIndexer/v0.6

Finally  the index is working .

The `search` failed with `jinahub://SimpleIndexer/v0.4` , upgrading to 0.6 successfully completed the `search`.

Are you aware of the MD5 issue?

**Comment by mapleeit** [comment]
Hey. @sephiartlist Thanks for reporting. We'll look into it.

**Comment by sephiartlist** [comment]
BTW I'm also getting an MD5 error on `jinahub://SimpleIndexer/v0.8`

**Comment by nomagick** [comment]
Hey @sephiartlist, Thanks for reaching us!
I have checked the md5sum of the version you mentioned, and it seems OK.
If I remember right, a bug in Jina was causing the bad md5 issue due to caching. 
And the bug was fixed weeks ago.
I suggest you update Jina to the latest version and try again.

**Comment by sephiartlist** [comment]
Hi @nomagick ,
Upgrading to jina==2.4.9 breaks the code in this repo example
```sh
frame_extractor@6863[E]:AttributeError("'tuple' object has no attribute 'append'")
 add "--quiet-error" to suppress the exception details
```

**Comment by nomagick** [comment]
@sephiartlist
Thanks for the reply.
The nearest release including the [patch](https://github.com/jina-ai/jina/commit/c8fa709e04a87d20046b6b9997d208418b157d2e) was `v2.1.11` and its latest minor release `v2.1.13`.
We'll soon fix this repo as well.

**Comment by sephiartlist** [comment]
@nomagick ,
thx! i've downgraded to jina==2.1.13 and all is working
